### ISSUE TITLE
Rancher host only partially monitored with agent

### ISSUE THREAD

**Issue by ckreutz** [infinityworksltd/Guide_Rancher_Monitoring#10]
Great implementation. It works really good. 

In my case the rancher server runs on an own host. I added a rancher agent, so prometheus runs on that host too. It shows some metrics, but for example not load average (e.g. node_load5). Does someone know what is the reason for that? I really need that working to send alerts.

**Comment by Rucknar** [comment]
If you load up the config page for Prometheus, check out the targets section, can it talk to the 'node-exporter' process? The node_* objects are populated through the prom/node-exporter container that should in theory be running on all hosts and contactable under the name 'node-exporter'

**Comment by ckreutz** [comment]
You got me on the right track. Thanks a lot. The host picked up a wrong IP address and this can be solved that way: http://docs.rancher.com/rancher/v1.2/en/faqs/troubleshooting/#are-the-ips-of-the-hosts-correct-in-the-ui
