### ISSUE TITLE
Upgrade to Grafana 4.0.2

### ISSUE THREAD

**Issue by Sturgelose** [infinityworksltd/Guide_Rancher_Monitoring#11]
Seems that there is a new Grafana version, and it simplifies all the procedure to create alerts, in comparison to use an alert manager with Prometheus. Could it be possible to update the template to this version? I can push a merge request!

**Comment by Rucknar** [comment]
Already one with Rancher to approve :) though I've left in alert manager as it's all a bit new to grafana and I'm not sure how stable it is yet.

**Comment by Rucknar** [comment]
https://github.com/rancher/community-catalog/pull/382
Merged!
