### ISSUE TITLE
rancher graphite setting doesn't work

### ISSUE THREAD

**Issue by Dmitry1987** [infinityworksltd/Guide_Rancher_Monitoring#12]
Hi,
thanks for the package and making this all work together :) 

I've tried to set the graphite host to influxDB as instructed, but see errors in rancher server containers (3 of them):
```
2017-02-02 16:47:37,729 WARN  [:] [] [] [] [xtrans-export-1] [o.j.embedded.output.GraphiteWriter  ] Failure to send result to graphite server 'HostAndPort{host='10.10.4.239:31656', port=2003}' with null java.net.UnknownHostException: 10.10.4.239:31656
```

in this message of course it's obvious it doesn't support setting custom port for database, but I tried first to use the internal ClusterIP of influx container, (which listens on 2003), then its host internal IP (which can be reached by master - but the NodePort it listens, is not 2003),  tried to insert nodePort there in setting, with local host IP, in hope it'll pick up the port setting, but it doesn't...

so, there are 2 possible places to fix it - either in rancher, to allow "port" in this API setting,
or to open port 2003 on same host and forward it to influx manually... 

what would you suggest as a fix?   I'm using K8s environment  (not sure whether this package supports K8s, or even made "only for K8s"?  how does this catalog works, every item shown in particular environment is supported by it?  or all shown but not all are compatible? :)  I'm new to rancher, sorry for noob questions)

thanks a lot in advance!

**Comment by Rucknar** [comment]
The above looks like a connectivity issue with the Rancher server container not being able to talk to the endpoint you've set. 

Good news however, in the latest rancher release this is set to get much easier (won't require infuxDB or API config). I'm expecting a merge to be accepted in the next few days then an updated catalog entry will be along with it (and updates to this guide.)

**Comment by Rucknar** [comment]
Hello, 

The catalog has now been updated to pull from the new `/metrics` endpoint, resulting in much simpler config and setup. I've updated the docs, i'll close this issue for now.
