### ISSUE TITLE
Monitor multiple hosts

### ISSUE THREAD

**Issue by apertureless** [infinityworksltd/Guide_Rancher_Monitoring#13]
It seems, that I can't really monitor multiple hosts.

I have 3 Servers. Ergo 3 hosts

**main server**
- rancher/server
- complete prometheus community catalog stack
- some other services

**do droplet 1**
- some services
- prometheus stack but only with node_exporter and cadvisor

**do droplet 2**
- some services
- prometheus stack but only with node_exporter and cadvisor

After adding the digital ocean droplets, the node_exporter and cadvisor were automatically deployed by rancher.

On the host stats dashboards, I can only select 1 host. And under the host health rancher widget, there is also only one visible.

So it seems the node_exporter seems not to work properly.

However I can access them with the rancher exporter over

`rancher_host_state{state="active"}`

**Comment by Rucknar** [comment]
Somewhat of a hunch, but if the server name doesn't match the regex for hosts, this could in theory happen. If your sure that Prometheus its-self can see the nodes:

In Grafana, click the settings icon and choose 'Templating', click edit on the nodes/host template.
You should see a regex field and below that, the matches that are captured, it might be worth adjusting the regex if it doesn't grab the match. 

Failing that, if you send me the server names, i'll take a look why they've not matched up.

**Comment by apertureless** [comment]
Found the issue. Seems to be related to rancher/agents if they run on same host as rancher server

**Comment by cianiandreadev** [comment]
@apertureless I am experiencing the same issue. I can only see only one of the two node running. How had you fixed that?
