### ISSUE TITLE
Stack status errors on clean deploy.

### ISSUE THREAD

**Issue by chris-garrett** [infinityworksltd/Guide_Rancher_Monitoring#14]
Just a heads up: 

I just tried Prometheus from the catalog today and while exploring I noticed that the dashboard: 'Stack Status - Prometheus' has errors. 7 of the 8 panels are showing 'no value' with an error of 'Multiple Series Error'. 

Rancher: 1.5.1
Prometheus Catalog: 2.1.0

**Comment by Rucknar** [comment]
Thanks for the heads up, i'm actually hoping to get a refreshed/updated catalog entry out next week. I'll make sure i test that page.

**Comment by chris-garrett** [comment]
When you post it let me know and I will help with testing it.

**Comment by Rucknar** [comment]
@chris-garrett Shouldn't be too long now, the pull request should go in the next few days.

**Comment by Rucknar** [comment]
@chris-garrett This is now released, let me know how you get on!

**Comment by Rucknar** [comment]
@chris-garrett I'll close this for now, re-open if you still have issues.

**Comment by chris-garrett** [comment]
I will test it out this week thx very much!
