### ISSUE TITLE
No Rancher statistics Data

### ISSUE THREAD

**Issue by mathieu-gilloots** [infinityworksltd/Guide_Rancher_Monitoring#16]
Hello,
On a fresh install of Prometheus with CATTLE_PROMETHEUS_EXPORTER to true on my rancher container, and port 9108 exposed on it, i've no data :(

When I browse on myhost:9108 i've got Graphite Exporter and I'm able to access metrics.

Thanks for your help.

**Comment by Rucknar** [comment]
It's likely to do with the URL prometheus is scraping. If you take a look at the 'Status > Targets' page. What is the status of the scrape target? Is it down?

Also, check the URL that's specified there, it should look like `http://x.x.x.x:9108/metrics`

**Comment by mathieu-gilloots** [comment]
Hello,
Yes the Container Metrics it's Down : 
http://rancher-server:9108/metrics (like in Status > Configuration)
In Prometheus stack i've my rancher server URL, why it will not take the info here ?
My standalone docker container for rancher is rancher_server (underscore, not "-"). maybe it's important ?

Thanks.

**Comment by Rucknar** [comment]
Perhaps the prometheus container can't resolve that rancher-server dns name?
Try use the servers IP, see if you get anywhere. I suspect that should resolve it.

**Comment by mathieu-gilloots** [comment]
@Rucknar Ok now, it's ok in 'Status > Targets' all is up. But "N/A" in grafana :
![image](https://cloud.githubusercontent.com/assets/1282351/25786818/2dc92a72-339b-11e7-96db-4b604c3770ec.png)

**Comment by Rucknar** [comment]
No `cattle_jvm`. What version of Rancher are you running out of interest?

**Comment by mathieu-gilloots** [comment]
v1.5.7

**Comment by Rucknar** [comment]
Okay, i suspect it's because the metric names weren't quite right in 1.5.7. It's possible the metrics are there but under different keys. 1.6.0 has a fix (https://github.com/rancher/rancher/commit/b4372ae583a3e4c43b79d82ff857545a91d7a101) that should standardise these names and make them more compliant with prometheus standards.

**Comment by mathieu-gilloots** [comment]
allright it's ok in 1.6.0. some stats are not available like network stats on Host stats but it's fine like that :)

**Comment by Rucknar** [comment]
Great stuff!

I'm picking through a few issues with the hosts extended/container extended dashboards this week.

**Comment by vision-ken** [comment]
You must specified `--name=rancher-server` when you run `docker run`, like this:
```
docker run -d -v /opt/rancher/mysql:/var/lib/mysql -p 8080:8080 -p 9108:9108 --restart=unless-stopped -e CATTLE_PROMETHEUS_EXPORTER=true --name=rancher-server rancher/server:v1.6.14
```
then  `http://rancher-server:9108/metrics` can work.
