### ISSUE TITLE
Questions about Enabling Prometheus metrics for the Rancher in HA

### ISSUE THREAD

**Issue by junkiebev** [infinityworksltd/Guide_Rancher_Monitoring#17]
1) In a multi-server Rancher Server cluster (3 running v1.5.9 in my instance) should we use

`-p 9108:9108 -e CATTLE_PROMETHEUS_EXPORTER=true`

on all servers?

2) Should 9109 be open on the rancher server container as well?

3) do we need to specify environmental variables for CATTLE_GRAPHITE_HOST and CATTLE_GRAPHITE_PORT still?

**Comment by Rucknar** [comment]
1. Very good question, i've not had the chance to test the variable on a rancher cluster. I'll ask the question though.

2. 9109? Not sure what for? 
3. You don't need those env variables for the prometheus metrics exporter now in cattle (As of 1.6.0>)

**Comment by junkiebev** [comment]
Ignore #2, The connection port is 9108 derp.
#1 appears to be fine - I'm running it on my entire cluster - because the catalog entry takes the IP of the rancher server as a parameter. I wonder what would happen if I pointed it at a load balancer...

**Comment by zot24** [comment]
So @junkiebev did you pointed to your LB and it just worked fine? did you manage to get metrics from all the nodes of the cluster?

Thanks!
