### ISSUE TITLE
Monitor multiple Environments

### ISSUE THREAD

**Issue by hwinkel** [infinityworksltd/Guide_Rancher_Monitoring#4]
How to monitor multiple Environments from one Central Promethues, Grafana, Influs Stack?

**Comment by Rucknar** [comment]
Good question, the template as it is now, won't monitor across environments. To do so, it requires two things:

1. Cross environment API key, specifiable through labels.
2. A solution to querying across multiple DNS instances in Rancher OR federation within Prometheus. 

Were actually working on resolving the above, hopefully we can get something sorted in the next 2-3 weeks.

**Comment by jifeon** [comment]
It would be very nice feature, guys! Any news here?

**Comment by nathan-v** [comment]
Is there any update? Cross-environment support would be great.

**Comment by Rucknar** [comment]
Tracking in https://github.com/infinityworksltd/prometheus-rancher-exporter/issues/2
