### ISSUE TITLE
Failed to find rancher-api-integration

### ISSUE THREAD

**Issue by jifeon** [infinityworksltd/Guide_Rancher_Monitoring#6]
I've copied `docker-compose.yml` and `rancher-compose.yml` to edit the affinity of some services from the catalog. I get this error for `rancher-compose create`:

```
INFO[0000] Creating stack prometheus                    
ERRO[0000] Failed to find rancher-api-integration       
ERRO[0000] Failed to find rancher-api-integration       
INFO[0000] Creating service ranch-eye                   
INFO[0001] Creating service node-exporter               
INFO[0001] Creating service prometheus-rancher-exporter 
INFO[0001] Creating service influxdb                    
ERRO[0001] Failed to find rancher-api-integration       
INFO[0001] Creating service prometheus                  
WARN[0002] Failed to find service rancher-api-integration to link to 
ERRO[0002] Failed to find rancher-api-integration       
INFO[0002] Creating service grafana                     
WARN[0003] Failed to find service rancher-api-integration to link to 
ERRO[0003] Failed to find rancher-api-integration       
ERRO[0003] Failed to find rancher-api-integration       
ERRO[0003] Failed to find rancher-api-integration       
WARN[0004] Failed to find service rancher-api-integration to link to 
ERRO[0004] Failed to find rancher-api-integration       
WARN[0004] Failed to find service rancher-api-integration to link to 
```

And it's true, I cannot see `rancher-api-integration` service for **1.1.0**, only for 1.0.3

**Comment by jifeon** [comment]
Looks like renaming `prometheus-rancher-exporter` to `rancher-api-integration` solves the issue

**Comment by Rucknar** [comment]
@jifeon interesting. Looks like this works due to implicit linking, not sure why it wasn't picked up however when being deployed through the catalog. We renamed this service with version 1.1.0 of the catalog entry, i'll fix the issue with the compose right now, thanks for reporting it!

**Comment by Rucknar** [comment]
@jifeon I've submitted a pull request for fix above, the linking isn't technically something that needs to be done in Rancher, it's nice though for visualising data flows in the UI and in the config so i personally still write it out. I'll close this once the pull request has been accepted.

**Comment by jifeon** [comment]
Thanks!

**Comment by Rucknar** [comment]
Missed an additional erroneous entry, this has now been merged. Closing the ticket, thanks for the heads up @jifeon !
