### ISSUE TITLE
Persist data for grafana and prometheus

### ISSUE THREAD

**Issue by jifeon** [infinityworksltd/Guide_Rancher_Monitoring#7]
Now if you have a host with grafana and prometheus restarted unexpectedly, you lose all the configuration and data. It would be nice to store configurations and data on docker volumes. Look at grafana authors [recommendation](http://docs.grafana.org/installation/docker/) for example.

**Comment by Rucknar** [comment]
@jifeon Apologies, missed this one. I've got a branch i'm testing with this amendment. Should merge this week.

**Comment by jclif** [comment]
Any update on this?

**Comment by kkvilekval** [comment]
I just ran into this.. we upgraded docker and rancher and all the containers restarted losing the entire history.   Can you provide a quick guide on how to configure for persistent data using 
host or convoy volumes?

**Comment by Rucknar** [comment]
https://github.com/infinityworksltd/Guide_Rancher_Monitoring/pull/15 Should resolve this.

**Comment by jifeon** [comment]
Thx, I solved that by creating my own configs long time ago. Do not think I will be able to test it soon. Maybe @kkvilekval can try it before closing the issue?

**Comment by Rucknar** [comment]
Merged, if anyone has an issue then raise a new ticket. Should hopefully be fixed!
